### PR TITLE
port #1683 to master - Fix publishing docker images

### PR DESCRIPTION
**Pull request by josephca**
port #1683 to master - Fix publishing docker images

### CODE REVIEW

**Comment by tetchel** [comment]
Something funky happened porting your commit from your 0.8 branch, can you make sure the only new commit is ec81e05 ?

**Comment by josephca** [comment]
> Something funky happened porting your commit from your 0.8 branch, can you make sure the only new commit is [ec81e05](https://github.com/eclipse/codewind/commit/ec81e05b395b05e4a903e20a8751b1162e108f2a) ?

I guess you're too fast? :) I fixed it in few mins.  Thanks!

**Comment by tetchel** [comment]
The ECA check is failing it thinks you have all these commits 

image

**Comment by josephca** [comment]
Replaced by https://github.com/eclipse/codewind/pull/1693. Closing it without merge.

**Pull request closed without merging**
