### PR TITLE
Stop streaming logs on close project

### PR DESCRIPTION
**Pull request by stalleyj**
Signed-off-by: Julie Stalley <julie_stalley@uk.ibm.com>

Added call to stop streaming logs when closing projects.

### CODE REVIEW

**Comment by ssh24** [comment]
I am still unable to test it with issues related to Che. Seeing multiple issues:
1. PFE takes way to long to come up
2. Also found out cannot set deployment registry because of buildah failures
```
[16/10/19 16:55:10 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/logger.js | Function Name: logProjectError | Line Number: 202] deploymentRegistryTest1: testDeploymentRegistry : 531 | buildah: symbol lookup error: buildah: undefined symbol: seccomp_api_set
```

So cannot test it if I can't create or export a project

**Comment by tobespc** [comment]
the template test failing is normally to do with appsody not returning the correct number of templates

**Comment by ssh24** [comment]
So I am still unable to get a workspace up and running to do the test https://github.com/eclipse/codewind/issues/704

**Comment by rajivnathan** [comment]
https://github.com/eclipse/codewind/issues/704 only occurs on master. Can you try the https://github.com/eclipse/codewind/pull/696 fix on the 0.5.0 branch to test that it fixes https://github.com/eclipse/codewind/issues/640? If that fix works we can port this fix for 0.5.0 and merge it into the 0.5.0 branch

**Comment by ssh24** [comment]
I was able to backport the PR to 0.5.0 and the fix works. See https://github.com/eclipse/codewind/pull/705#issuecomment-542870220

We can land both the PR on master and 0.5.0

Thank you @stalleyj for the fix!

**Pull request merged**
