### PR TITLE
allow debug mount of portal source

### PR DESCRIPTION
**Pull request by makandre**
Signed-off-by: Andrew Mak <makandre@ca.ibm.com>

Resolves https://github.com/eclipse/codewind/issues/1149
Requires PR https://github.com/eclipse/codewind-installer/pull/240

### CODE REVIEW

**Comment by makandre** [comment]
@tobespc @rajivnathan Could you please take a look at this PR?

**Comment by rajivnathan** [comment]
Do we really need a mount for dev? Part of the reason for making the switch to cwctl is to bring the dev environment closer to the prod environment. The main difference between dev and prod currently is nodemon and other dev dependencies that stick around. Adding a mount to the container sounds like a significant departure from that.

Also, you don't need to rebuild and restart because we already have nodemon running in dev mode. You'd only need to copy the source into the container for nodemon to pick it up. For Turbine development we have `push` scripts to handle that. See https://github.com/eclipse/codewind/blob/755a13a4aa067e9b2790ffc3c87943e0ae0fffd5/src/pfe/file-watcher/server/package.json#L22

Think we just need something similar for portal?

**Comment by makandre** [comment]
If you’re copying the entire dist folder over, how is it that much different than mounting the folder? (Tho I didn’t know about this push script in turbine, that’s useful)

Well I did make this available only if —dev is specified, so it’s not going to do the mount by default. I guess a mount is just a convenience (tho especially when working on extension code since I can just save a file to trigger the restart and reload the extension)

But ok, if turbine is doing push local style then we should keep it consistent. I’ll change it to that.

**Comment by makandre** [comment]
Superseded by #1288

**Pull request closed without merging**
