### PR TITLE
Add Code Coverage for PFE into Jenkins

### PR DESCRIPTION
**Pull request by tobespc**
Signed-off-by: Toby Corbin <corbint@uk.ibm.com>

### CODE REVIEW

**Comment by james-wallis** [comment]
**Title:** Add Code Coverage for PFE into Jenkins
### Summary
* Added functionality to generate the code coverage for PFE unit and API tests in Jenkins, also optionally the file-watcher unit test coverage.
  * Had to enhance the `generate_complete_coverage.js` file to report the file-watcher code optionally.
  * Uses images with the tag `:test` as the PFE needs a change to run code coverage, doing it this way means that the original images `:latest` will be pushed without changes made for testing.
* Made the running of code coverage optional
  * Stops it being run when developing if wanted
  * Fixed bug in Jenkins where the `apitest` run would overwrite the previous `unittest` run. In the future this fix might need to be more complex (i.e. different `.nyc_output` directories) but for now this is fine. - We don't care about the `apitest` local `.nyc_output` as the code coverage is inside the container.

**Comment by james-wallis** [comment]
Been advised by @liamchampton to open up a PR on my own branch so that the PR isn't off toby's branch.
https://github.com/eclipse/codewind/pull/1882

**Comment by james-wallis** [comment]
This can be closed once the #1882 branch is accepted in.

**Comment by liamchampton** [comment]
> Been advised by @liamchampton to open up a PR on my own branch so that the PR isn't off toby's branch.
> #1882

With proof of this running change successfully passing on this PR it is best to create a new PR based off of your own branch so we are not merging from a branch called `liam`.

**Comment by james-wallis** [comment]
Other PR https://github.com/eclipse/codewind/pull/1882 has been accepted, this can be closed.

**Comment by hhellyer** [comment]
Closing as merged under #1882.

**Pull request closed without merging**
