### PR TITLE
updated open source used in 0.12 release

### PR DESCRIPTION
**Pull request by NikCanvin**
## What type of PR is this ? 

- [ ] Bug fix
- [ ] Enhancement

## Any special notes for your reviewer ?
**Note**: Please do not merge until we get approvals from each reviewer. @NikCanvin and @josephca will make the change on other Codewind repositories.

### CODE REVIEW

**Comment by josephca** [comment]
@tobespc I guess you missed the special note that I added - no worries though. :)
@elsony @sghung Could you do the review even if it was merged already? thanks in advance. 

`Note: Please do not merge until we get approvals from each reviewer. @NikCanvin and @josephca will make the change on other Codewind repositories.`

**Comment by tobespc** [comment]
oops, sorry @josephca I missed that :-(

**Comment by NikCanvin** [comment]
still awaiting review (comment your feedback) from @sghung and @elsony ...

**Comment by elsony** [comment]
Looks good

**Pull request merged**
