### PR TITLE
Revert back old readWorkspaceSettings function definition

### PR DESCRIPTION
**Pull request by ssh24**
### Description

The readWorkspaceSettings function definition was accidentally changed which caused a regression in our functional test suite. Reverting it back. Original commit https://github.com/eclipse/codewind/commit/60a98e94327fceae75f868a099295b7038077189#diff-1c61507dfacef770d56960208ce7b95fR273

### CODE REVIEW

**Comment by ssh24** [comment]
@maysunfaisal Could you PTAL?

**Comment by maysunfaisal** [comment]
This fixes Turbine functional tests for PR https://github.com/eclipse/codewind/pull/603

**Comment by ssh24** [comment]
I don't know what the actual description of `writeWorkspaceSettings` function is.

**Comment by ssh24** [comment]
I updated to a meaningful message I thought made sense. PTAL.

**Comment by maysunfaisal** [comment]
Acc to https://github.com/eclipse/codewind/pull/603/files; the function writes the new setting to the workspace settings file and invalidates the cache

**Comment by rajivnathan** [comment]
How about this?

```
/**
     * @function
     * @description Write the provided workspace settings to the workspace settings file.
     * @param newWorkspaceSettings  <Required | Object>: New workspace settings to write to the file
     * @example await filewatcher.writeWorkspaceSettings(newWorkspaceSettings);
     *
     * @returns Promise<workspaceSettings.IWorkspaceSettingsSuccess | workspaceSettings.IWorkspaceSettingsFailure>
     * Response codes:
     *  @property 200: Successfully wrote the file
     *  @property 500: Error when attempting to write the workspace settings file
     *
     */
```

**Comment by ssh24** [comment]
@rajivnathan Updated the description now. Could you PTAL?

**Pull request merged**
