### PR TITLE
Fix run docker statement

### PR DESCRIPTION
**Pull request by ssh24**
Potential fix for https://github.com/eclipse/codewind/issues/1062

I also saw this on linux and this PR this solved it.

Signed-off-by: ssh24 <sakib@ibm.com>

### CODE REVIEW

**Comment by ssh24** [comment]
@maysunfaisal Could you PTAL?

**Comment by maysunfaisal** [comment]
sorry for double approval/comment. Thought it was the master PR

**Comment by ssh24** [comment]
Still think it should go into 0.6.1 because it was seen consistently when doing performance testing over a long run period

**Comment by rajivnathan** [comment]
I think it should be done for all projects and for both 0.6.1 and master @eyuen thoughts?

**Comment by rajivnathan** [comment]
As discussed, we'll target this fix only for master since it turned out to be too late for 0.6.1

**Pull request closed without merging**
